# Use an official Python runtime as a parent image
FROM python:3.12

# Install PDM
RUN pip install --upgrade pip
RUN pip install pdm

# Set the working directory in the container
WORKDIR /usr/src/app


# Copy the rest of your application's code
COPY . .


# Install dependencies using PDM
RUN pdm install 

# Make port available to the world outside this container
EXPOSE 8001
